AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI C2-less Serverless Application

Resources:
  CoordinatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: coordinator.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /coordinator
            Method: post